### ISSUE TITLE
improve resolver context caching strategy

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#10]
Revisit the current resolver context caching strategy, see if it can be improved.

Initial version: https://codereview.appspot.com/201840043/ changes:

* [x] ~~use reference counting and throw cache full exception and remove the MRU~~
* [x] ~~handle the caching of file system objects~~
* [x] ~~move VFS file system back-end specific code out of resolver, note that the resolver helper should fail to import if the back-end is not available.~~
* [x] ~~add tests~~
* [x] ~~fix too many open files issue~~
* [x] ~~fix maximum number of cached values reached~~
* [x] ~~remove direct usage of file IO objects by file entry objects~~

Think about:

* handling of temporary file copies e.g. back-ends that require to make a working copy (e.g. sqlite3)
* FileSystemSearcher get mount point from file system e.g. GetMountPoint() ?
* ~~make GetFileEntryByPathSpec a class method?~~ no
* should file object file IO objects explicitly close the resolved file_object ? E.g. https://github.com/log2timeline/dfvfs/blob/master/dfvfs/file_io/qcow_file_io.py#L34

After care:

* [x] ~~update https://github.com/log2timeline/dfvfs/wiki/Internals rename OpenFileObject and OpenFileSystem in resolver helper~~
* [x] ~~fix Exception RuntimeError: RuntimeError(u'Object not cached.',) notifications in plaso~~
* [ ] remove resolver context Empty function
  * leaving as-is for now

**Comment by joachimmetz** [comment]
Think about:

* moving VFS file system back-end specific code out of resolver, note the resolver helper should fail to import if the back-end is not available.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfvfs/commit/29d7e8a76ced50e273987d36e22b1c447e6c3083

**Comment by aozsyn** [comment]
Consumers of this code (much of Plaso's parser stack) mostly error out on the small 128-element cache size and aren't handling the exception, failing to parse individual files rather than evicting cache or retrying.  I'm unsure whether to submit this as a new bug against Plaso or comment on this issue, so have elected the latter.  Example trace (of thousands while parsing a Linux image):

2015-03-04 15:17:26,876 [WARNING] (Worker_0  ) PID:21514 <worker> [olecf] Unable to process file: type: OS, location: /mnt/path/to/file with error: Maximum number of cached values reached..
2015-03-04 15:17:26,876 [ERROR] (Worker_0  ) PID:21514 <worker> Maximum number of cached values reached.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/plaso/engine/worker.py", line 123, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "/usr/lib/python2.7/site-packages/plaso/parsers/olecf.py", line 63, in Parse
    file_object = file_entry.GetFileObject()
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/file_entry.py", line 125, in GetFileObject
    self.path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "/usr/lib/python2.7/site-packages/dfvfs/file_io/file_io.py", line 79, in open
    self._resolver_context.CacheFileObject(path_spec, self)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/context.py", line 52, in CacheFileObject
    self._file_object_cache.CacheObject(path_spec.comparable, file_object)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/cache.py", line 78, in CacheObject
    raise errors.CacheFullError(u'Maximum number of cached values reached.')
CacheFullError: Maximum number of cached values reached.

Setting maximum_number_of_file_objects to an arbitrarily high number (e.g. 2^18) masked the issue and allowed Plaso to continue processing.

**Comment by joachimmetz** [comment]
Are you running the latest plaso? 

Work is in progress to clean up the plaso parsers to behave correctly with the cache limit. A remove from cache is forced in plaso in the time being, hence the situation you describe should not happen with the current version of plaso.

**Comment by aozsyn** [comment]
I'm running plaso-1.2.0-2 from the CERT forensics repository.  Looking at their spec file, it's actually running slightly more recent code than the 1.2.0 release on 2015/12/20.

**Comment by joachimmetz** [comment]
You'll need https://github.com/log2timeline/plaso/commit/e34f4bb222eac759f8675331ec722d2174143a5e

**Comment by aozsyn** [comment]
Thanks for the help!
